{% set name = "extension-helpers" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e7d9c8f71804edd7ecd05b5d59a5b504f6e24867970abfc12771242eed76ebcc

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools >=43.0.0
    - setuptools_scm >=6.2
  run:
    - python >=3.8
    - setuptools >=40.2
    - tomli >=1.0.0

test:
  imports:
    - extension_helpers

about:
  home: https://github.com/astropy/extension-helpers
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Utilities for building and installing packages with compiled extensions
  doc_url: https://extension-helpers.readthedocs.io/
  dev_url: https://github.com/astropy/extension-helpers

extra:
  recipe-maintainers:
    - astrofrog
    - mwcraig
    - bsipocz
