{% set name = "extension-helpers" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ca1bfac67c79cf4a7a0c09286ce2a24eec31bf17715818d0726318dd0e5050e6

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools >=43.0.0
    - setuptools_scm >=6.2
  run:
    - python >=3.6
    - setuptools >=40.2

test:
  imports:
    - extension_helpers

about:
  home: https://github.com/astropy/extension-helpers
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Utilities for building and installing packages with compiled extensions
  doc_url: https://extension-helpers.readthedocs.io/
  dev_url: https://github.com/astropy/extension-helpers

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
    - mwcraig
    - bsipocz
