{% set name = "extension-helpers" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 37701c2055bbdb5b5d157541239980300694e59c95e8caf9a6533b26378d1024

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=43.0.0
    - setuptools_scm >=6.2
  run:
    - python >={{ python_min }}
    - setuptools >=40.2
    - tomli >=1.0.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - extension_helpers

about:
  home: https://github.com/astropy/extension-helpers
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Utilities for building and installing packages with compiled extensions
  doc_url: https://extension-helpers.readthedocs.io/
  dev_url: https://github.com/astropy/extension-helpers

extra:
  recipe-maintainers:
    - astrofrog
    - mwcraig
    - bsipocz
